window.MP_CONFIG = {
  supabaseUrl: 'https://cajkvtaajbjvzggfxkzj.supabase.co',
  supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhamt2dGFhamJqdnpnZ2Z4a3pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY4NTYxMjQsImV4cCI6MjEwMjQzMjEyNH0.zqquGGtLKkq3pK4anSoZq2FAIwMOmYU6pc31KTixnhQ'
};
